### ISSUE TITLE
Error: DEPTH_ZERO_SELF_SIGNED_CERT

### ISSUE THREAD

**Issue by desimmons** [codius/codius-host#60]
I am following the examples in the readme.md file of the codius-cli repository. After setting up a local codius host, I get the following error message when I try to upload:

Error: DEPTH_ZERO_SELF_SIGNED_CERT
    at SecurePair.<anonymous> (tls.js:1381:32)
    at SecurePair.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:980:10)
    at CleartextStream.read [as _read](tls.js:472:13)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write](tls.js:369:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:602:24)
    at flow (_stream_readable.js:611:7)
    at Socket.pipeOnReadable (_stream_readable.js:643:5)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)

How can we resolve this problem?

**Comment by polarisft** [comment]
Hi have the same issue did you ever get a solution for this?

**Comment by justmoon** [comment]
It's an error related to using a self-signed cert. Have you tried `CODIUS_UNAUTHORIZED_SSL=true codius upload --hosts https://self-signed-host.com` as suggested in the README?

Otherwise you can also try `NODE_TLS_REJECT_UNAUTHORIZED=0 codius upload`

**Comment by polarisft** [comment]
Thanks that worked
